"""the change into nullable true to user_type_id

Revision ID: 0eb66c1c01a9
Revises: bd0bdab6efc7
Create Date: 2025-07-12 15:34:09.863988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb66c1c01a9'
down_revision: Union[str, None] = 'bd0bdab6efc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
