"""added coordinate to cities and sitrcitcs

Revision ID: 20f5ce1d82cf
Revises: 2df01b230c51
Create Date: 2025-07-12 20:35:33.183049

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20f5ce1d82cf"
down_revision: Union[str, None] = "2df01b230c51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("coordinate", sa.String(), nullable=True))
    op.add_column("districts", sa.Column("coordinate", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("districts", "coordinate")
    op.drop_column("cities", "coordinate")
    # ### end Alembic commands ###
