"""added coordinate

Revision ID: 2df01b230c51
Revises: 0eb66c1c01a9
Create Date: 2025-07-12 19:47:28.942524

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2df01b230c51"
down_revision: Union[str, None] = "0eb66c1c01a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regions", sa.Column("coordinate", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "coordinate")
    # ### end Alembic commands ###
