"""added pending users

Revision ID: 3eb97fe8c17b
Revises: 5402d4efd4fd
Create Date: 2025-07-14 11:30:21.479356

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3eb97fe8c17b"
down_revision: Union[str, None] = "5402d4efd4fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_entries", sa.Column("pending_user_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        op.f("otp_entries_user_id_fkey"), "otp_entries", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "otp_entries",
        "pending_users",
        ["pending_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("otp_entries", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "otp_entries",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "otp_entries", type_="foreignkey")
    op.create_foreign_key(
        op.f("otp_entries_user_id_fkey"),
        "otp_entries",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("otp_entries", "pending_user_id")
    # ### end Alembic commands ###
