"""removed the cities

Revision ID: 5a06e3f9a6f0
Revises: 20f5ce1d82cf
Create Date: 2025-07-12 21:00:57.220654

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a06e3f9a6f0"
down_revision: Union[str, None] = "20f5ce1d82cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint(op.f("schools_city_fkey"), "schools", type_="foreignkey")

    op.drop_column("schools", "city")

    op.drop_table("cities")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools", sa.Column("city", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("schools_city_fkey"),
        "schools",
        "cities",
        ["city"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("parent_region", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "modified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("coordinate", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_region"],
            ["regions.id"],
            name=op.f("cities_parent_region_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cities_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("cities_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
