"""added school ids

Revision ID: 75e093e4a7aa
Revises: 8c2d007d5745
Create Date: 2025-07-13 14:41:35.766388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75e093e4a7aa"
down_revision: Union[str, None] = "8c2d007d5745"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_infos", sa.Column("school_id", sa.UUID(), nullable=False))
    op.drop_constraint(
        op.f("student_infos_school_fkey"), "student_infos", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "student_infos", "schools", ["school_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("student_infos", "school")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_infos",
        sa.Column("school", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "student_infos", type_="foreignkey")
    op.create_foreign_key(
        op.f("student_infos_school_fkey"),
        "student_infos",
        "schools",
        ["school"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("student_infos", "school_id")
    # ### end Alembic commands ###
