"""added to school ids

Revision ID: 797404c08d89
Revises: 75e093e4a7aa
Create Date: 2025-07-13 14:42:41.018748

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "797404c08d89"
down_revision: Union[str, None] = "75e093e4a7aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student_infos", sa.Column("father_id", sa.UUID(), nullable=True))
    op.add_column("student_infos", sa.Column("mother_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("student_infos_mother_fkey"), "student_infos", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("student_infos_father_fkey"), "student_infos", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "student_infos", "users", ["mother_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "student_infos", "users", ["father_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("student_infos", "father")
    op.drop_column("student_infos", "mother")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_infos",
        sa.Column("mother", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "student_infos",
        sa.Column("father", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "student_infos", type_="foreignkey")
    op.drop_constraint(None, "student_infos", type_="foreignkey")
    op.create_foreign_key(
        op.f("student_infos_father_fkey"),
        "student_infos",
        "users",
        ["father"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("student_infos_mother_fkey"),
        "student_infos",
        "users",
        ["mother"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("student_infos", "mother_id")
    op.drop_column("student_infos", "father_id")
    # ### end Alembic commands ###
