"""added notifications to preferences

Revision ID: 8c2d007d5745
Revises: ad09add02c61
Create Date: 2025-07-13 14:07:33.732692

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c2d007d5745"
down_revision: Union[str, None] = "ad09add02c61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences",
        sa.Column(
            "notifications_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "notifications_enabled")
    # ### end Alembic commands ###
