"""removed policy  ids to schools

Revision ID: ad09add02c61
Revises: fd838a98badc
Create Date: 2025-07-13 00:38:55.793582

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad09add02c61"
down_revision: Union[str, None] = "fd838a98badc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schools", "policy_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schools", "policy_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
