"""added is active to devices

Revision ID: c13650c31090
Revises: 3eb97fe8c17b
Create Date: 2025-07-14 17:55:58.815307

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c13650c31090"
down_revision: Union[str, None] = "3eb97fe8c17b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_devices", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_devices", "is_active")
    # ### end Alembic commands ###
