"""added role name to users

Revision ID: c68128c8c903
Revises: 0f6df2ecccc0
Create Date: 2025-07-13 23:14:57.804037

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c68128c8c903"
down_revision: Union[str, None] = "0f6df2ecccc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_role_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_role_name")
    # ### end Alembic commands ###
