"""added ids to schools

Revision ID: fd838a98badc
Revises: 5a06e3f9a6f0
Create Date: 2025-07-12 21:43:33.034735

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd838a98badc"
down_revision: Union[str, None] = "5a06e3f9a6f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schools", sa.Column("region_id", sa.UUID(), nullable=False))
    op.add_column("schools", sa.Column("district_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("schools_district_fkey"), "schools", type_="foreignkey")
    op.drop_constraint(op.f("schools_region_fkey"), "schools", type_="foreignkey")
    op.create_foreign_key(
        None, "schools", "districts", ["district_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "schools", "regions", ["region_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("schools", "district")
    op.drop_column("schools", "region")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schools", sa.Column("region", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "schools", sa.Column("district", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "schools", type_="foreignkey")
    op.drop_constraint(None, "schools", type_="foreignkey")
    op.create_foreign_key(
        op.f("schools_region_fkey"),
        "schools",
        "regions",
        ["region"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("schools_district_fkey"),
        "schools",
        "districts",
        ["district"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("schools", "district_id")
    op.drop_column("schools", "region_id")
    # ### end Alembic commands ###
